### ISSUE TITLE
A few more features, if it is of interest

### ISSUE THREAD

**Issue by mrseanryan** [brendannee/noobgallery#17]
hello @brendannee - in case it is of interest:

To use noobgallery for my own photos, I added a few features, in a fork:

https://github.com/mrseanryan/noobgallery

The features are:

* about page
* error page
* gallery summary & tags (via optional gallery.json for each gallery)
* hide the image download button
* do not upload original images
* reduce largest size from 3000x to 2400x
* add optional copyright watermark
* add optional fotomoto store links
* tech: improved error handling during build
* tech: support CloudFront without the need for lambda function

Sharing in case it is of use.

thank you for creating this library !

**Comment by brendannee** [comment]
These sound like great features and improvements.  Could you make a pull request with these features so I can merge them in?

**Comment by mrseanryan** [comment]
hi @brendannee  glad to here you like this.

In case you want to see how it looks, this is my photo site = https://everydayphotos.net/

Have opened a PR #18

**Comment by brendannee** [comment]
I updated all dependencies and updated the gulp file to ESM format.

I also added a few updates to make the About page optional and handle cases without copyright text. Check out the latest release and let me know if there are any issues https://github.com/brendannee/noobgallery/releases/tag/0.4.0
